lllooch-dev.georgi.k/config/routes.rb
CMS::Application.routes.draw do

  #get 'dpd' => 'dpd#show'
  #get 'dellin' => 'dellin#show'

  # роуты для wysiwyg-редактора
  mount RedactorRails::Engine => '/redactor_rails'

  match 'payed', to: 'admin/acquiring#result', via: [:get, :post]

  scope "(:locale)", locale: ContentRouter.locales do
    # поиск?
    # TODO проверить
    get "search/search"

    # backbone-каталог товаров
    post "catalog/fetch" => "content/catalogs#fetch", as: :catalog_fetch

    # backbone-каталог постов
    post "blogs/fetch" => "content/blogs#fetch", as: :blog_fetch
  end

  scope "(:locale)", locale: ContentRouter.locales do
    # поиск
    get "search" => 'search#search', as: :search
  end

  scope '(:locale)/preorder', controller: 'content/preorder', locale: ContentRouter.locales do
    post '', action: :show, as: :preorder_form
    patch '', action: :finish, as: :preorder_finish
  end

  # корзина
  scope '(:locale)/cart', locale: ContentRouter.locales do
    # покупка товара
    post 'buy' => 'content/carts#buy', as: :cart_buy
    get 'buy' => 'content/carts#buy', as: :cart_get_buy

    # сохранение данных о товарах
    post 'update' => 'content/carts#update', as: :cart_update

    # расчет доставки
    patch 'delivery' => 'content/carts#delivery', as: :cart_delivery

    # удаление товара из корзины
    delete controller: 'content/carts', action: :remove_good, as: :cart_remove

    # предзаказ подтверждение
    #scope :preorder, controller: 'content/preorder' do
    #  patch '', action: :finish, as: :preorder_finish
    #end

    # заказ подтверждение
    scope :order, controller: 'content/order' do
      patch '', action: :finish, as: :order_finish
    end
  end

  # рут для админа
  get '/admin' => 'admin/welcome#index'

  # рут для контент-менеджера
  get '/cm' => 'cm/welcome#index', as: :cm_root


  # контент-менеджер
  namespace :cm do
    # категории постов
    resources :post_categories, path: 'blogs' do
      # посты
      get 'items', on: :member, action: :index, as: :items

      # выбор локали для правки
      get ':locale', on: :member, action: :edit, as: 'languaged'

      # сортировка
      post 'order', on: :collection, as: 'order'
    end

    # посты
    resources :posts do
      # блоки
      resources :blocks, controller: 'post_blocks' do
        get ':locale', on: :member, action: :edit, as: :languaged
        post 'order', on: :collection, as: 'order'
      end

      post 'order', on: :collection, as: 'order'
      get ':locale', on: :member, action: :edit, as: :languaged
    end
  end

  # админ
  namespace :admin do
    # рут
    get '' => 'welcome#index', as: 'root'

    # дебаг шаблонов письем
    match 'mailer(/:action(/:id(.:format)))' => 'mailer#:action', via: :get

    scope :acquiring, controller: :acquiring, as: :acquiring do
      get '', action: :index
      get '/cart', action: :card, as: :card
      get '/mac', action: :mac, as: :mac
      post '', action: :result, as: :result
    end

    # меню
    resources :menus

    # заказы, предзаказы
    resources :orders, :preorders, except: [:create, :edit, :update]

    # статусы заказов
    resources :order_statuses do
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # типы доставки
    resources :delivery_types, :payment_types do
      post 'order', on: :collection, as: 'order'
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # категории товаров
    resources :good_categories, path: 'catalog' do
      get 'items', on: :member, action: :index, as: :items
      post 'order', on: :member, action: :order, as: :order
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # группы свойств
    resources :property_types do
      get 'items', on: :member, action: :index, as: :items
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # меню
    resources :menus do
      # элементы меню
      resources :menu_items
    end

    # свойства, языки, страницы, теги, параметры, переводы
    resources :properties, :languages, :pages, :tags, :settings, :translations do
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # элементы меню, 3д-вьюхи, файлы, варианты, материалы
    resources :menu_items, :three60s, :files, :variants, :materials do
      get ':locale', on: :member, action: :edit, as: 'languaged'
      post 'order', on: :collection, as: 'order'
    end

    # дизайнеры
    resources :designers do
      # товары
      resources :design_items do
        get ':locale', on: :member, action: :edit, as: 'languaged'
      end

      get ':locale', on: :member, action: :edit, as: 'languaged'
      post 'order', on: :collection, as: 'order'
    end


    # товары
    resources :goods do
      # файлы
      resources :files, only: [:new, :create]

      # 3д-вьюхи
      resources :three60s, only: [:new, :create]

      # варианты
      resources :variants, only: [:new, :create]

      post 'order', on: :collection, as: 'order'
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

  end

  # подключение языкового роутера
  LanguageRouter.reload
  unless LanguageRouter.routes.nil?
    LanguageRouter.routes.each do |r|
      get r
    end
  end


  # подключение контентного роутера
  ContentRouter.reload
  unless ContentRouter.routes.nil?
    scope "(:locale)", locale: ContentRouter.locales do
      ContentRouter.routes.each do |r|
        get r.except(:page, :applies_to, :active)
      end
    end
  end

  # редиректы товаров
  #GoodsRouter.reload
  unless GoodsRouter.routes.nil?
    GoodsRouter.routes.each do |r|
      get r[:route] => redirect(r[:redirect_to])
    end
  end


  match '*a', :to => 'content#show404', via: [:get, :post]
end

lllooch-dev.georgi.k/app/controllers/admin/order_statuses_controller.rb
# CRUD статусов заказа
# на данный момент нигде не используется
class Admin::OrderStatusesController < Admin::BaseController
  include MultilingualController
  before_action :set_order_status, only: [:show, :edit, :update, :destroy]

  # GET /order_statuses
  # GET /order_statuses.json
  def index
    @order_statuses = OrderStatus.all
  end

  # GET /order_statuses/1
  # GET /order_statuses/1.json
  def show
  end

  # GET /order_statuses/new
  def new
    @order_status = OrderStatus.new
  end

  # GET /order_statuses/1/edit
  def edit
  end

  # POST /order_statuses
  # POST /order_statuses.json
  def create
    @order_status = OrderStatus.new(order_status_params)

    respond_to do |format|
      if @order_status.save
        format.html { redirect_to admin_order_statuses_url, notice: 'Order status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order_status }
      else
        format.html { render action: 'new' }
        format.json { render json: @order_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_statuses/1
  # PATCH/PUT /order_statuses/1.json
  def update
    respond_to do |format|
      if @order_status.update(order_status_params)
        format.html { redirect_to admin_order_statuses_url, notice: 'Order status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_statuses/1
  # DELETE /order_statuses/1.json
  def destroy
    @order_status.destroy
    respond_to do |format|
      format.html { redirect_to admin_order_statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_status
      @order_status = OrderStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def safe_params
      [:name, :priority, :type]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_status_params
      permit_params
    end
end

lllooch-dev.georgi.k/app/views/admin/order_statuses/_form.html.erb
<%= language_prompt %>

<%= simple_form_for [:admin, @order_status], url: @order_status.new_record? ? admin_order_statuses_path : admin_order_status_path(@order_status), :html => {:class => 'form-horizontal'} do |f| %>
    <%= form_errors f %>

    <%= simple_fields_for 'order_status', @order_status do |f| %>

        <% Globalize.with_locale(@locale.slug) do %>
            <%= f.input :name %>
        <% end %>

        <%= f.input :type, collection: OrderStatus.types.invert %>

        <%= language_input f %>
    <% end %>

    <div class="form-actions">
      <%= f.button :submit, save_or_update(@order_status), :class => 'btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  admin_order_statuses_path, :class => 'btn' %>
    </div>
<% end %>

lllooch-dev.georgi.k/app/views/admin/order_statuses/edit.html.erb
<div class="page-header">
  <%= language_select %>
  <h1>Правка статуса заказа: <%= @order_status.name %></h1>
</div>

<%= render :partial => 'form' %>

lllooch-dev.georgi.k/app/views/admin/order_statuses/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to (plus_icon + ' Статус'),
                new_admin_order_status_path,
                :class => 'btn' %>
  </div>

  <h1>Статусы заказа</h1>
</div>

<% if @order_statuses.empty? %>
    <div class="well">
      Опаньки, ни одного статуса не найдено :(
    </div>
<% else %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Статус</th>
        <th width="60px"></th>
      </tr>
      </thead>
      <tbody>

      <% @order_statuses.each do |order_status| %>
          <tr>
            <td>
              <%= order_status.name %>
            </td>

            <td>
              <%= link_to pencil_icon,
                          edit_admin_order_status_path(order_status), :class => 'btn btn-mini' %>

              <%= link_to trash_icon(true),
                          admin_order_status_path(order_status),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-mini btn-danger' %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>  

lllooch-dev.georgi.k/app/views/admin/order_statuses/new.html.erb
<div class="page-header">
  <h1>Новый статус заказа</h1>
</div>
<%= render :partial => 'form' %>

lllooch-dev.georgi.k/app/views/admin/order_statuses/show.html.erb
<%- model_class = OrderStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @order_status.type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:priority) %>:</strong></dt>
  <dd><%= @order_status.priority %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              order_statuses_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_order_status_path(@order_status), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              order_status_path(@order_status),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>