fantasycapital/config/routes.rb
require "resque_web"

Main::Application.routes.draw do

  
  
  ActiveAdmin.routes(self)
  
  
  ResqueWeb::Engine.eager_load!

  mount ResqueWeb::Engine => "/resque_web"

  get "users/leadboard"
  get "users/signin_popup"

  get "splash/index", as: :splash
  root to: "contests#browse"

  get "terms/", :controller => "terms", :action => "index"
  get "privacy-policy/", :controller => "privacy_policy", :action => "index"

  devise_for :users, :controllers => {:sessions => 'sessions', :registrations => 'registrations' }

  get '/users/subregion_options' => 'users#subregion_options'
  resources :pages do
    collection do
      get :rules_faq
    end
  end
  resources :entries do
    member do
        post 'admin'
    end
  end

  scope(:path => 'admin', :as => 'admin') do
    get 'games', to: 'admin#games'
    get 'entries', to: 'admin#entries'
    get 'contests', to: 'admin#contests'
    get 'users', to: 'admin#users'
    get "/", to: "admin#index"
  end

  resources :lineups do
    member do
      get :export
    end
    resource :entries
  end
  resources :players, only: [] do
    member do
      get :stats
    end
  end
  resources :contests, only: [:index, :show] do
    collection do
      get 'browse'
    end
  end

  resources :waiting_lists, only: [:new, :create, :show] do
    collection do
      get :invite
      post :inviting
    end
  end

  resources :accounts, only: [:create, :edit, :show, :index] do
    collection do
      get :new_cc
      get :profile
      get :history
      get :withdraw
      get :add_fund

      resources :credit_cards
      post 'credit_cards/deposit' => 'credit_cards#deposit'

      get 'bank_accounts/withdrawal' => 'bank_accounts#withdrawal', :as => :withdrawal
      post 'bank_accounts/withdrawal' => 'bank_accounts#withdrawal_post'
      resources :bank_accounts
    end
  end

   resources :projections do
     collection do
       get "with_stats/:sport_name" => 'projections#with_stats'
       get "stats_by_game/:sport_name" => 'projections#stats_by_game', :as => :stats_by_game
       get ":sport_name" => 'projections#index' # funky, index has a parameter? does this work?
     end
     resources :projection_by_stats do
       resources :projection_by_stat_and_games do
         resources :projection_breakdowns
       end
     end
   end

  resources :password_resets

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

fantasycapital/app/views/layouts/_admin_header.html.erb
<%= render 'shared/topbar' %>
<%# we should find a way to combine this better with shared/_header.html.erb %>
<header>
  <div class='container'>
    <h1 class='logo'>
      <%= link_to root_path do%>
          <%= image_tag 'main_logo.png', alt: 'Fantasy Capital' %>
      <% end %>
    </h1>

    <% if current_user %>
        <div class='balanceBlock'>
          <strong>Your Balance</strong>
          <strong class='ajax-modal pull-right' id='add-fund' data-url="<%= add_fund_accounts_path %>">
            Add Funds
            <i class="glyphicon glyphicon-plus"></i>
          </strong>
          <h1>
            <sup>$</sup>
            <%= number_to_currency(current_user.account_balance, unit: '') %>
          </h1>
        </div>
    <% end %>

    <div style="clear:both;"></div>
    <div class='navbar navbar-default capitalnavbar' role="navigation">
      <div class='navbar-header'>
        <button class='navbar-toggle' data-target=".mainMenu" data-toggle="collapse" type="button">
          <span class='sr-only'>Toggle navigation</span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
      </div>
      <div class='navbar-collapse collapse mainMenu'>
        <ul class='nav navbar-nav'>
          <li class='<%= menu_classes 'home' %>'>
            <%= link_to 'Home', root_path %>
            <div class="line"></div>
          </li>
          <li class='<%= menu_classes 'admin' %>'>
            <%= link_to 'Admin', admin_path %>
            <div class="line"></div>
          </li>
          <li class='<%= menu_classes 'games' %>'>
            <%= link_to 'Games', admin_games_path %>
            <div class="line"></div>
          </li>
          <li class='<%= menu_classes 'entries' %>'>
            <%= link_to 'Entries', admin_entries_path %>
            <div class="line"></div>
          </li>
          <li class='<%= menu_classes 'contests' %>'>
            <%= link_to 'Contests', admin_contests_path %>
            <div class="line"></div>
          </li>
          <li class='<%= menu_classes 'users' %>'>
            <%= link_to 'Users', admin_users_path %>
            <div class="line"></div>
          </li>

          <li class="welcome-box">
            <% if user_signed_in? %>
                <div class="welcome-text">
                  <a href="javascript:void(0)">
                    Welcome, <span class="first-name"><%= current_user.username%></span>
                  </a>
                </div>

                <ul class="usermenu">
                  <li>
                    <a href="/users/sign_out" data-method="delete" class="sign-out">
                      Log Out
                    </a>
                  </li>
                </ul>
            <% else %>
                <!--<%= link_to "SIGN UP" , new_user_registration_path, :class => 'link' %>
              <a href="#" class="link">/</a>
              <%= link_to "SIGN IN" , new_user_session_path, :class => 'link' %>
              <span class="arrow">&#10095;</span>-->
                <%= link_to "JOIN NOW" , '/', :class => 'link require-signin' %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

fantasycapital/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= page_title %></title>
  <!--Le HTML5 shim, for IE6-8 support of HTML elements-->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"></script>
  <script src="//https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->

  <%= tag :meta, :name => 'stripe-key', :content => Rails.configuration.stripe[:publishable_key] %>

  <%= javascript_include_tag 'https://d3dy5gmtp8yhk7.cloudfront.net/2.1/pusher.min.js' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
  <%= javascript_include_tag 'https://js.stripe.com/v1/' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</head>

<body class='<%=page_class%>' id='<%= page_id %>'>
<%= render 'layouts/admin_header' %>
<div class='container capitalcontent'>
  <%= yield %>
</div>
<%= render 'shared/footer' %>
</body>

<%= yield :after_js %>

</html>

fantasycapital/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= page_title %></title>
    <meta charset="utf-8">
    <!--[if lt IE 9]>
      <%= javascript_include_tag 'html5shiv.min.js' %>
      <%= javascript_include_tag 'respond.min.js' %>
    <![endif]-->

    <%= tag :meta, :name => 'stripe-key', :content => Rails.configuration.stripe[:publishable_key] %>

    <%= javascript_include_tag 'https://d3dy5gmtp8yhk7.cloudfront.net/2.1/pusher.min.js' %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= yield :head %>
    <%= javascript_include_tag 'https://js.stripe.com/v1/' %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </head>

  <body class='<%=page_class%>' id='<%= page_id %>'>
    <%= render 'shared/header' %>
    <div class='container'>
      <%= yield :banner %>
      <div class="capitalcontent">
        <% if flash[:notice] %>
            <div class="alert alert-success"><%= flash[:notice] %></div>
        <% end %>
        <% if flash[:alert] %>
            <div class="alert alert-danger"><%= flash[:alert] %></div>
        <% end %>

        <%= yield %>
      </div>
    </div>
    <%= render 'shared/footer' %>
    <div class="ajax-loader" style="display:none;">
      <img src="<%= image_path("ajax-loader.gif") %>">
    </div>
    <noscript>
      <div class="no-js-banner">
        <img src="<%= image_path("js-disabled-banner.gif") %>">
      </div>
    </noscript>
    <%= yield :templates %>
  </body>

  <%= yield :after_js %>

</html>

fantasycapital/app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>
  <!--Le HTML5 shim, for IE6-8 support of HTML elements-->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"></script>
  <script src="//https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

  <body class='<%=page_class%>' id='<%= page_id %>'>
    <%= yield %>
  </body>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</html>