lllooch-dev.georgi.k/config/routes.rb
CMS::Application.routes.draw do

  #get 'dpd' => 'dpd#show'
  #get 'dellin' => 'dellin#show'

  # роуты для wysiwyg-редактора
  mount RedactorRails::Engine => '/redactor_rails'

  match 'payed', to: 'admin/acquiring#result', via: [:get, :post]

  scope "(:locale)", locale: ContentRouter.locales do
    # поиск?
    # TODO проверить
    get "search/search"

    # backbone-каталог товаров
    post "catalog/fetch" => "content/catalogs#fetch", as: :catalog_fetch

    # backbone-каталог постов
    post "blogs/fetch" => "content/blogs#fetch", as: :blog_fetch
  end

  scope "(:locale)", locale: ContentRouter.locales do
    # поиск
    get "search" => 'search#search', as: :search
  end

  scope '(:locale)/preorder', controller: 'content/preorder', locale: ContentRouter.locales do
    post '', action: :show, as: :preorder_form
    patch '', action: :finish, as: :preorder_finish
  end

  # корзина
  scope '(:locale)/cart', locale: ContentRouter.locales do
    # покупка товара
    post 'buy' => 'content/carts#buy', as: :cart_buy
    get 'buy' => 'content/carts#buy', as: :cart_get_buy

    # сохранение данных о товарах
    post 'update' => 'content/carts#update', as: :cart_update

    # расчет доставки
    patch 'delivery' => 'content/carts#delivery', as: :cart_delivery

    # удаление товара из корзины
    delete controller: 'content/carts', action: :remove_good, as: :cart_remove

    # предзаказ подтверждение
    #scope :preorder, controller: 'content/preorder' do
    #  patch '', action: :finish, as: :preorder_finish
    #end

    # заказ подтверждение
    scope :order, controller: 'content/order' do
      patch '', action: :finish, as: :order_finish
    end
  end

  # рут для админа
  get '/admin' => 'admin/welcome#index'

  # рут для контент-менеджера
  get '/cm' => 'cm/welcome#index', as: :cm_root


  # контент-менеджер
  namespace :cm do
    # категории постов
    resources :post_categories, path: 'blogs' do
      # посты
      get 'items', on: :member, action: :index, as: :items

      # выбор локали для правки
      get ':locale', on: :member, action: :edit, as: 'languaged'

      # сортировка
      post 'order', on: :collection, as: 'order'
    end

    # посты
    resources :posts do
      # блоки
      resources :blocks, controller: 'post_blocks' do
        get ':locale', on: :member, action: :edit, as: :languaged
        post 'order', on: :collection, as: 'order'
      end

      post 'order', on: :collection, as: 'order'
      get ':locale', on: :member, action: :edit, as: :languaged
    end
  end

  # админ
  namespace :admin do
    # рут
    get '' => 'welcome#index', as: 'root'

    # дебаг шаблонов письем
    match 'mailer(/:action(/:id(.:format)))' => 'mailer#:action', via: :get

    scope :acquiring, controller: :acquiring, as: :acquiring do
      get '', action: :index
      get '/cart', action: :card, as: :card
      get '/mac', action: :mac, as: :mac
      post '', action: :result, as: :result
    end

    # меню
    resources :menus

    # заказы, предзаказы
    resources :orders, :preorders, except: [:create, :edit, :update]

    # статусы заказов
    resources :order_statuses do
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # типы доставки
    resources :delivery_types, :payment_types do
      post 'order', on: :collection, as: 'order'
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # категории товаров
    resources :good_categories, path: 'catalog' do
      get 'items', on: :member, action: :index, as: :items
      post 'order', on: :member, action: :order, as: :order
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # группы свойств
    resources :property_types do
      get 'items', on: :member, action: :index, as: :items
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # меню
    resources :menus do
      # элементы меню
      resources :menu_items
    end

    # свойства, языки, страницы, теги, параметры, переводы
    resources :properties, :languages, :pages, :tags, :settings, :translations do
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # элементы меню, 3д-вьюхи, файлы, варианты, материалы
    resources :menu_items, :three60s, :files, :variants, :materials do
      get ':locale', on: :member, action: :edit, as: 'languaged'
      post 'order', on: :collection, as: 'order'
    end

    # дизайнеры
    resources :designers do
      # товары
      resources :design_items do
        get ':locale', on: :member, action: :edit, as: 'languaged'
      end

      get ':locale', on: :member, action: :edit, as: 'languaged'
      post 'order', on: :collection, as: 'order'
    end


    # товары
    resources :goods do
      # файлы
      resources :files, only: [:new, :create]

      # 3д-вьюхи
      resources :three60s, only: [:new, :create]

      # варианты
      resources :variants, only: [:new, :create]

      post 'order', on: :collection, as: 'order'
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

  end

  # подключение языкового роутера
  LanguageRouter.reload
  unless LanguageRouter.routes.nil?
    LanguageRouter.routes.each do |r|
      get r
    end
  end


  # подключение контентного роутера
  ContentRouter.reload
  unless ContentRouter.routes.nil?
    scope "(:locale)", locale: ContentRouter.locales do
      ContentRouter.routes.each do |r|
        get r.except(:page, :applies_to, :active)
      end
    end
  end

  # редиректы товаров
  #GoodsRouter.reload
  unless GoodsRouter.routes.nil?
    GoodsRouter.routes.each do |r|
      get r[:route] => redirect(r[:redirect_to])
    end
  end


  match '*a', :to => 'content#show404', via: [:get, :post]
end

lllooch-dev.georgi.k/app/models/good_category.rb
class GoodCategory < Category
  has_and_belongs_to_many :goods
end

lllooch-dev.georgi.k/app/controllers/admin/good_categories_controller.rb
# CRUD категорий товаров
class Admin::GoodCategoriesController < Admin::BaseController
  include MultilingualController
  before_action :set_category, only: [:show, :edit, :update, :destroy, :order]

  # GET /categories
  # GET /categories.json
  def index
    @collections = GoodCategory.all
    @items = Good.all.to_a

    if params[:id]
      if params[:id] == 'main'
        @items.select! { |i| i.on_main }
      else
        @collection = GoodCategory.find(params[:id])
        @items = @items.delete_if { |i| i.good_category.select { |c| c == @collection }.empty? }.sort_by{|g| g.category_good_weight }
      end
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = GoodCategory.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = GoodCategory.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_good_categories_url, notice: 'GoodCategory was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_good_categories_url, notice: 'GoodCategory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def order
    errors = []

    if order_params
      order_params.each_with_index do |id, weight|
        category_good = CategoryGood.find_or_initialize_by good_id: id, good_category_id: @category.id


        unless category_good.update(weight: weight)
          errors << category_good.errors
        end
      end
    end

    respond_to do |format|
      if errors.empty?
        format.json { head :no_content }
      else
        format.json { render json: errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_good_categories_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = GoodCategory.find(params[:id])
  end

  def safe_params
    [:name, :slug, :parent_id, :title, :heading, :keywords, :description]
  end

  # Never trust parameters from the scary internet, only allow the white list through.

  def order_params
    params.require(:order)
  end

  def good_category_params
    category_params
  end

  def category_params
    permit_params
  end
end

lllooch-dev.georgi.k/app/views/admin/good_categories/_form.html.erb
<%= language_prompt %>

<%= simple_form_for [:admin, @category], :html => { :class => 'form-horizontal' } do |f| %>
  <%= form_errors f %>

  <%= tabs [[:main, 'Основное'], [:meta, 'META']] %>

  <%= tab_contents do %>
    <%= tab_pane :main, {active: true} do %>
      <%= f.input :name %>
      <%= f.input :slug if @category.id? %>
      <%= f.association :parent, 
        collection: GoodCategory.with_translations('ru').select{|c| c != @category}, 
        include_blank: 'Отсутствует' if false %>
    <% end %>

    <%= tab_pane :meta do %>
      <% Globalize.with_locale(@locale.slug) do %>
        <%= f.input :title %>
        <%= f.input :heading %>
        <%= f.input :keywords %>
        <%= f.input :description %>
      <% end %>
    <% end %>
  <% end %>

  <%= language_input f %>

  <div class="form-actions">
    <%= f.button :submit, save_or_update(@category), :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
        admin_good_categories_path, :class => 'btn' %>
  </div>
<% end %>

lllooch-dev.georgi.k/app/views/admin/good_categories/edit.html.erb
<div class="page-header">
  <%= language_select %>
  <h1>Правка категории: <%= @category.name %></h1>
</div>
<%= render :partial => 'form' %>

lllooch-dev.georgi.k/app/views/admin/good_categories/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to (plus_icon + ' Категория'),
            new_admin_good_category_path,
            :class => 'btn' %>
    <%= link_to (plus_icon + ' Товар'),
            new_admin_good_path,
            :class => 'btn' %>
  </div>
  <h1>Каталог товаров</h1>
</div>

<div class="row">
  <div class="span9">
    <% if @items.empty? %>  
      <div class="well">
        Опаньки.. А товаров-то и нету :(
      </div>
    <% else %>
      <table class="table table-striped table-nested" data-type="nested" data-nested-url="<%= @collection.present? ? order_admin_good_category_path(@collection) : order_admin_goods_path %>">
        <thead>
          <tr>
            <th>Товар</th>
            <th class="center">Категории</th>
            <th width="18%" class="center">Дизайнеры</th>
            <th width="60px" class="center">Цена</th>
            <th width="60px"></th>
          </tr>
        </thead>
        
        <% @items.each do |good| %>
          <tbody data-nested="item" data-nested-id="<%= good.id %>">
            <tr>
              <td>
                <%= with_pic good, good.thumb %>
              </td>
              <td class="center">
                <%= link_list(good.good_category) %>
              </td>
              <td class="center">
                <%= link_list(good.designer) %>
              </td>
              <td class="center"><%= good.price %></td>
              <td>
                <%= link_to pencil_icon,
                    edit_admin_good_path(good), :class => 'btn btn-mini' %>

                <%= link_to trash_icon(true),
                    admin_good_path(good),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-mini btn-danger' %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    <% end %>
  </div>

  <div class="span3">
    <ul class="nav nav-tabs nav-stacked">
      <li<%= ' class=active' if !@collection && !params[:id] %>>
        <%= link_to('Все товары', admin_good_categories_path) %>
      </li>

      <li<%= ' class=active' if params[:id] == 'main' %>>
        <%= link_to('Товары на главной', items_admin_good_category_path({id: 'main'})) %>
      </li>

      <% @collections.each do |collection| %>
        <li<%= ' class=active' if @collection && @collection == collection %>>
          <div class="controls">
            <%= link_to(pencil_icon,
                edit_admin_good_category_path(collection), :class => 'btn btn-link') %>

            <%= link_to(trash_icon,
                admin_good_category_path(collection),
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-link') %>
          </div>
          
            <%= link_to (collection.name + tag(:br) + content_tag(:small, collection.path, class: :muted)).html_safe,   
                items_admin_good_category_path(collection) %>
          </a>
        </li>
      <% end %>
    </ul>
  </div>
</div>

lllooch-dev.georgi.k/app/views/admin/good_categories/new.html.erb
<div class="page-header">
  <h1>Новая категория</h1>
</div>
<%= render :partial => 'form' %>

lllooch-dev.georgi.k/app/views/admin/good_categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:parent_id) %>:</strong></dt>
  <dd><%= @category.parent_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @category.type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @category.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:heading) %>:</strong></dt>
  <dd><%= @category.heading %></dd>
  <dt><strong><%= model_class.human_attribute_name(:keywords) %>:</strong></dt>
  <dd><%= @category.keywords %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @category.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              categories_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_path(@category), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>